version: '3' 
services:
  rabbitmq:
    image: rabbitmq:3.12.13-management
    container_name: rabbitmq
    restart: always
    mem_limit: 350m
    environment:
      - TZ=Asia/Taipei
    network_mode:  "host"  
    #ports:
    #  - 5672:5672
    #  - 15672:15672
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 20s
      timeout: 5s
      retries: 10